version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  courier:
    build:
      context: .
      dockerfile: courier.dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "1997:1997"
  csv_parser:
    build:
      context: .
      dockerfile: csv_parser.dockerfile
    env_file: .env
    networks:
      - default
    ports:
      - "1996:1996"

volumes:
  data: